### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by epost**
Cobbled together some info from various (vintage) websites. It could probably do with a bit of revision, as I don't actually know anything about this project.

### CODE REVIEW

**Comment by epost** [comment]
Oh, dang, I noticed the ``doc`` dir just after submitting this. :(

**Comment by anyahelene** [comment]
Doc or no doc, a README is a good thing.

**Comment by epost** [comment]
Right. Perhaps it would make sense to ``git mv doc/README README.md`` but I think that's best left up to those in the know. :)

**Comment by PaulKlint** [comment]
Hi Erik, thanks for your contribution. Several publications about PDB are in the pipeline and your request will act as wake up call that we have to upgrade the current docs.

**Comment by epost** [comment]
Interesting, I'll keep an eye out! :)

**Pull request closed without merging**
